### ISSUE TITLE
catgirl: Occasionally a malformed password may be generated

### ISSUE THREAD

**Issue by MissPasture** [CuteAP/fediverse.express#2]
If we get really lucky, we might generate a password YAML doesn't like, like `g:0P6Z6a.r6Z7T.fkJ3U843tr-WCwH:`.

We have two options here:
* Only make passwords alphanumeric
* Surround generated passwords in quotes (?)

**Comment by puff-fan-420** [comment]
What about just using 128 bits of randomness and encoding as base62? That shouldn’t have any conflicting characters with yaml and would be reasonably secure (if using secure rand).

**Comment by MissPasture** [comment]
We do this in the Ansible playbook:

https://github.com/CuteAP/fediverse.express/blob/master/catgirl/roles/postgres/tasks/main.yml#L12

Theoretically, I could just set `chars` to `ascii_uppercase` and `ascii_lowercase` but it looks like quoting probably works so I'll try that
